name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: |
          npm install
          npm list

      - name: Show workspace contents
        run: |
          echo "Current directory: $(pwd)"
          ls -la
          echo "Source directory:"
          ls -la src/
          echo "Demo directory:"
          ls -la demo/

      - name: Format code
        run: |
          echo "Formatting code..."
          npm run format
          git diff --exit-code || (echo "Code formatting issues found. Please run 'npm run format' locally and commit the changes." && exit 1)

      - name: Run TypeScript type check
        run: |
          echo "Running type check..."
          npm run typecheck
        continue-on-error: true

      - name: Run linting
        run: |
          echo "Running linting..."
          npm run lint
        continue-on-error: true

      - name: Run tests
        run: |
          echo "Running tests..."
          npm test
        continue-on-error: true

      - name: Build package
        run: |
          echo "Building package..."
          npm run build
          echo "Build output:"
          ls -la dist/ 